name: CI
on: [push]
env:
  CI: true
  NODE_ENV: test
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    - name: Setup Node.js for use with actions
      uses: actions/setup-node@v1.1.0
      with:
        version: 10.x
    - uses: actions/cache@v1
      if: always()
      with:
        path: ~/.cache
        key: ${{ runner.os }}-home-${{ hashFiles('package-lock.json') }}
    - name: Install dependencies
      run: npm install
    - name: Build
      run: |
        set -ex
        npm run lint
        npm run build
    - name: Publish
      if: startsWith(github.ref, 'refs/tags/v')
      run: |
        echo "//registry.npmjs.org/:_authToken=${NPM_AUTH_TOKEN}" > ~/.npmrc
        npm publish
